<a href="https://colab.research.google.com/github/Immanuel2022/ML-Projects-Basic/blob/main/Assignment_2_Numpy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# Array Creation:
# Create a 2D Numpy array of shape (6, 8) with random integer values between 20 and 150. Find the mean, median, and standard deviation of the array.

import numpy as np

arr = np.random.randint(20,150, size=(6,8))
arr

array([[113,  94, 129, 122, 111, 142,  45,  41],
       [105,  79, 110,  35,  80,  59,  70,  74],
       [ 43,  88,  42,  56,  73,  93,  92,  70],
       [126,  22,  78,  21,  41, 119, 105,  61],
       [ 69, 136, 121,  60,  43, 131,  41,  73],
       [ 79,  85,  39, 105,  87,  79,  39, 130]])

In [5]:
# Column Statistics:
# Using the above-created array, calculate the sum and variance of each column.

arr.sum()


3856

In [6]:
arr.std()

32.74671315143281

In [10]:
# Subsetting Columns:
# Select columns 3 through 6 of the array and calculate the product of their values.

arr1 = arr[:,3:7]
arr1

array([[122, 111, 142,  45],
       [ 35,  80,  59,  70],
       [ 56,  73,  93,  92],
       [ 21,  41, 119, 105],
       [ 60,  43, 131,  41],
       [105,  87,  79,  39]])

In [12]:
arr1.prod()

5613142391501111296

In [14]:
# Flatten the Array:
# Flatten the array into a 1D array and reshape it into both (2, 24) and (24, 2) shapes.

arr1.shape

(6, 4)

In [16]:
arr1.ravel()

array([122, 111, 142,  45,  35,  80,  59,  70,  56,  73,  93,  92,  21,
        41, 119, 105,  60,  43, 131,  41, 105,  87,  79,  39])

In [18]:
arr1.reshape(2,12)

array([[122, 111, 142,  45,  35,  80,  59,  70,  56,  73,  93,  92],
       [ 21,  41, 119, 105,  60,  43, 131,  41, 105,  87,  79,  39]])

In [19]:
arr1.reshape(12,2)

array([[122, 111],
       [142,  45],
       [ 35,  80],
       [ 59,  70],
       [ 56,  73],
       [ 93,  92],
       [ 21,  41],
       [119, 105],
       [ 60,  43],
       [131,  41],
       [105,  87],
       [ 79,  39]])

In [21]:
# Reshaping to 3D:
# Reshape the original 2D array into a 3D array of shape (4, 3, 2).

arr1.reshape(4,3,2)

array([[[122, 111],
        [142,  45],
        [ 35,  80]],

       [[ 59,  70],
        [ 56,  73],
        [ 93,  92]],

       [[ 21,  41],
        [119, 105],
        [ 60,  43]],

       [[131,  41],
        [105,  87],
        [ 79,  39]]])

In [24]:
# Combine 1D Arrays:
# Create two 1D arrays of size 15 with random integers between 5 and 50. Combine them into a single 2D array with three columns.

arr2 = np.random.randint(5,50,size = (15))
arr2


array([21, 43, 39, 13, 49, 34, 47, 25, 39, 47, 10,  8, 38,  8, 41])

In [25]:
arr3 = np.random.randint(5,50,size = (15))
arr3

array([ 6, 12, 47, 38, 24, 18, 41, 10, 47, 33, 25, 37, 13, 23, 38])

In [29]:
arr4 = np.column_stack((arr2, arr3))
arr4

array([[21,  6],
       [43, 12],
       [39, 47],
       [13, 38],
       [49, 24],
       [34, 18],
       [47, 41],
       [25, 10],
       [39, 47],
       [47, 33],
       [10, 25],
       [ 8, 37],
       [38, 13],
       [ 8, 23],
       [41, 38]])

In [30]:
arr4.reshape(10,3)

array([[21,  6, 43],
       [12, 39, 47],
       [13, 38, 49],
       [24, 34, 18],
       [47, 41, 25],
       [10, 39, 47],
       [47, 33, 10],
       [25,  8, 37],
       [38, 13,  8],
       [23, 41, 38]])

In [34]:
# Dot Product:
# Calculate the dot product of the two 1D arrays created in the previous question after reshaping them to (3, 5).
arr5 = arr2.reshape(3,5)
arr5

array([[21, 43, 39, 13, 49],
       [34, 47, 25, 39, 47],
       [10,  8, 38,  8, 41]])

In [35]:
arr6 = arr3.reshape(3,5)
arr6

array([[ 6, 12, 47, 38, 24],
       [18, 41, 10, 47, 33],
       [25, 37, 13, 23, 38]])

In [36]:
arr5*arr6

array([[ 126,  516, 1833,  494, 1176],
       [ 612, 1927,  250, 1833, 1551],
       [ 250,  296,  494,  184, 1558]])

In [37]:
# Using Linspace:
# Use np.linspace to create a 1D array with 20 equally spaced values between 10 and 100. Reshape this array into a 4x5 matrix.

arr7 = np.linspace(10,100,20)
arr7

array([ 10.        ,  14.73684211,  19.47368421,  24.21052632,
        28.94736842,  33.68421053,  38.42105263,  43.15789474,
        47.89473684,  52.63157895,  57.36842105,  62.10526316,
        66.84210526,  71.57894737,  76.31578947,  81.05263158,
        85.78947368,  90.52631579,  95.26315789, 100.        ])

In [38]:
arr7.reshape(4,5)

array([[ 10.        ,  14.73684211,  19.47368421,  24.21052632,
         28.94736842],
       [ 33.68421053,  38.42105263,  43.15789474,  47.89473684,
         52.63157895],
       [ 57.36842105,  62.10526316,  66.84210526,  71.57894737,
         76.31578947],
       [ 81.05263158,  85.78947368,  90.52631579,  95.26315789,
        100.        ]])

In [39]:
# Normalize an Array:
# Generate an array of 30 random floats between 0.5 and 5. Normalize the array so that all values fall between -1 and 1.

arr8 = np.random.rand(20)

#(xi - mean) / std

u = np.mean(arr8)
s = np.std(arr8)

(arr8-u)/s

array([-0.55418213,  0.1704653 ,  0.95925662,  2.09786065, -0.70090368,
       -0.91677058,  0.81617063, -0.44823857, -0.2625367 , -2.18372801,
        0.35712158, -0.80922582,  1.22956587,  0.20771248,  0.92076406,
        1.03545373, -1.1341107 , -1.07052321,  0.67950581, -0.39365733])

In [40]:
# Population Analysis:
# Simulate population data of 8 cities over 15 years using a random integer array (15x8, values between 100,000 and 1,000,000).
#Calculate the average population for each city.

arr9 = np.random.randint(100000,1000000,size=(15,8))
arr9

array([[531773, 355797, 288389, 891434, 735369, 211196, 181594, 839071],
       [106221, 138074, 738683, 144875, 556560, 543031, 528673, 383415],
       [310111, 118169, 634619, 243660, 475153, 941073, 272887, 572315],
       [915764, 885010, 157380, 416828, 174386, 857113, 323639, 884955],
       [448909, 733043, 715943, 920526, 879093, 184383, 330755, 142024],
       [305244, 528863, 654940, 594677, 166630, 384633, 824339, 866776],
       [548560, 468132, 698205, 796802, 303512, 984927, 712832, 690118],
       [724862, 335104, 701935, 317470, 523754, 389835, 477924, 766130],
       [633651, 605841, 349801, 207770, 138794, 839290, 546087, 652474],
       [336336, 138732, 322423, 860547, 907506, 717734, 890488, 985971],
       [148261, 492772, 101990, 985337, 273360, 465619, 718147, 170197],
       [801097, 671038, 429987, 544314, 110696, 139169, 345914, 720973],
       [107124, 845939, 767318, 233429, 118378, 231656, 213622, 677649],
       [320340, 546476, 382879, 143800, 610096, 923

In [42]:
arr9.mean(axis=0)

array([430629.6       , 509603.93333333, 496969.4       , 493901.        ,
       458589.4       , 543638.86666667, 535423.4       , 650515.13333333])