<a href="https://colab.research.google.com/github/Immanuel2022/ML-Projects-Basic/blob/main/Numpy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# 1. Filtering and Mapping (Prime Numbers)
# Given the array:

# arr = np.array([13, 22, 31, 44, 57, 71, 83, 91])
# Use filter and a lambda function to retain only the prime numbers from the array.
# Use map and lambda to compute the square of each prime number.
# Create a new NumPy array from the squared values and compute its standard deviation using np.std.

import numpy as np
arr = np.array([13, 22, 31, 44, 57, 71, 83, 91])

import math

def is_prime(x):
  flag = True
  for i in range(2,x):
    if x%i == 0:
      flag = False
  return True if flag == True else False


result1 = list(filter(is_prime,arr))
result1

result2 = list(map(lambda x:x**2,result1))
result2


[169, 961, 5041, 6889]

In [4]:
arr = np.array(result2)

np.std(arr)

2792.005730653145

In [8]:
# Boolean Masking and np.where
# Given the array:


arr = np.array([25, 12, 7, 30, 45, 18, 50])
# Use boolean masking to extract all numbers greater than 20.
# Use np.where to replace numbers divisible by 5 with 1, and others with 0.

#boolean masking
arr1 = arr[arr>20]

np.where(arr1%5==0, 1, 0)

array([1, 1, 1, 1])

In [11]:
# 3. Row and Column-Wise Means
# Given the 2D array:


arr = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90]])
# Compute the overall mean using np.mean.
# Compute the row-wise mean.
# Compute the column-wise mean.

np.mean(arr)

# Compute the row-wise mean.
np.mean(arr,axis=1)

# Compute the column-wise mean.
np.mean(arr,axis=0)

array([40., 50., 60.])

In [13]:
# 4. Percentile Calculation
# Given the array:


x = np.array([5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

# Calculate the 25th, 50th, and 75th percentiles using np.percentile.

print(np.percentile(x,25),np.percentile(x,50),np.percentile(x,75))

27.5 50.0 72.5


In [16]:
# 5. Dictionary Comprehension with Numpy
# Given the rainfall data:


rainfall = {'CityX': [150, 160, 170], 'CityY': [100, 110, 120], 'CityZ': [200, 210, 220]}

# Create a dictionary where the key is the city name, and the value is the total rainfall using np.sum.

{i:np.sum(j) for i,j in rainfall.items()}

# Create another dictionary where the key is the city name, and the value is the average rainfall for cities with average rainfall > 150.
{i:np.mean(j) for i,j in rainfall.items() if np.mean(j)>150}

{'CityX': 160.0, 'CityZ': 210.0}

In [18]:
# 6. Seaborn Dataset Analysis
# Using the penguins dataset from Seaborn:


import seaborn as sns
df = sns.load_dataset('penguins')
dataset = df.to_numpy()
# Extract the first column and compute its mean using np.mean.
# Extract the last column and find the unique values using np.unique.

df.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen             NaN            NaN                NaN   
4  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  
0       3750.0    Male  
1       3800.0  Female  
2       3250.0  Female  
3          NaN     NaN  
4       3450.0  Female

In [19]:
# Extract the first column and compute its mean using np.mean.

np.mean(dataset['bill_length_mm'])

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [20]:
# 7. Correlation Coefficient
# Given the following NumPy arrays:


x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])

# Compute the correlation coefficient using np.corrcoef.
np.corrcoef(x,y)

array([[1., 1.],
       [1., 1.]])

In [23]:
# 8. Statistical Functions
# Given the 2D array:


arr = np.array([[5, 10, 15],
               [20, 25, 30],
                 [35, 40, 45]])
# Compute the median for the entire array.
np.median(arr)

# Compute the row-wise median.
np.median(arr,axis=1)

# Compute the column-wise median.
np.median(arr,axis=0)

array([20., 25., 30.])

In [25]:
# 9. Timing Runtime
# Compare the runtime of the following operations using a large NumPy array:


arr = np.array(range(1, 1000000))

# Use Python's built-in sum() to compute the sum of the array.

%%timeit
sum(arr)
# Use np.sum() to compute the sum of the array.

UsageError: Line magic function `%%timeit` not found.


In [26]:
arr = np.array(range(1, 1000000))

# Use np.sum() to compute the sum of the array.
%%timeit
np.sum(arr)

UsageError: Line magic function `%%timeit` not found.


In [27]:
# 10. Data Transformation with np.where
# Given the array:


arr = np.array([3, 6, 9, 12, 15, 18, 21])
# Use np.where to create a new array where numbers divisible by 3 are replaced with 'divisible' and others with 'not divisible'.

arr = np.array([1,2,3,4,5,6,7,8,9,10])

np.where(arr%3==0,'divisible','not divisible')

array(['not divisible', 'not divisible', 'divisible', 'not divisible',
       'not divisible', 'divisible', 'not divisible', 'not divisible',
       'divisible', 'not divisible'], dtype='<U13')